site_name: DCE Documentation
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Quickstart: quickstart.md
  - How To: howto.md
  - DCE IAM Policies: iam-policies.md
  - Deploy with Terraform: terraform.md
  - "API Reference": api-documentation.md
  - "API Auth": api-auth.md
  - "SNS Lifecycle Events": sns.md
  - Local Development: develop.md
  - Contribution Guidelines: CONTRIBUTING.md
  - Changes: CHANGELOG.md
theme: readthedocs
extra_css:
  - custom.css